// @generated by protoc-gen-enumrepro v0.0.1 with parameter "target=ts"
// @generated from file repro/v1/repro.proto (package repro.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

export const MyCustomOption = {
  name: "MyCustomOption",
};
export const MyMessage = {
  name: "MyMessage",
  fieldBehavior: 1,
  myCustomOption: {"val":"MY_ENUM_SECOND"},
};
